spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10
      
      
jmsexample:
    routes:
      bridge:
        - id: firstBridge
          entry: "jms:queue:customer.example.esb?selector=EVENT='one'"
          exit: jms:queue:esb.methode.one.customer2      
        - id: secondBridge
          entry: "jms:queue:customer.example.esb?selector=EVENT='two'"
          exit: jms:queue:esb.methode.two.customer2  
        - id: firstTopicBridge
          entry: "jms:topic:customer.example.esb?clientId=2&durableSubscriptionName=bar2&selector=EVENT='one'"
          exit: jms:queue:esb.methode.one.customer      
        - id: secondTopicBridge
          entry: "jms:topic:customer.example.esb?clientId=1&durableSubscriptionName=bar1&selector=EVENT='two'"
          exit: jms:queue:esb.methode.two.customer   
      consuming:
        - id: consumingCustomerOne
          entry: jms:queue:esb.methode.one.customer
        - id: consumingCustomerTwo
          entry: jms:queue:esb.methode.two.customer
        - id: consumingCustomer2One
          entry: jms:queue:esb.methode.one.customer2
        - id: consumingCustomer2Two
          entry: jms:queue:esb.methode.two.customer2  
      producing:    
        - id: produceQueue1
          cron: 0/10+*+*+*+*+?
          exit: jms:queue:customer.example.esb
          additionalHeaders:
             EVENT: "one" 
        - id: produceQueue2
          cron: 0/10+*+*+*+*+?
          exit: jms:queue:customer.example.esb
          additionalHeaders:
             EVENT: "two"
        - id: produceTopic1
          cron: 0/10+*+*+*+*+?
          exit: jms:topic:customer.example.esb
          additionalHeaders:
             EVENT: "one"   
        - id: produceTopic2
          cron: 0/10+*+*+*+*+?
          exit: jms:topic:customer.example.esb
          additionalHeaders:
             EVENT: "two"              