language: java
dist: trusty
services:
  - docker
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
  
global:
  - TRAVISCI_SCRIPT_DIR=/tmp/ci_scripts


before_install:
  - mkdir -p $TRAVISCI_SCRIPT_DIR
  - wget https://gist.githubusercontent.com/nolte/33a1a963d8161db0641b59f26d794e01/raw/dockerhub_deploy.sh -O $TRAVISCI_SCRIPT_DIR/dockerhub_deploy.sh
  - chmod u+x $TRAVISCI_SCRIPT_DIR/*

script: mvn clean install -PwithDocker
