spring:
  cloud:
    config:
      server:
        native:
          searchLocations: /var/config-repos/base
          
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${registry_host:registryservice}:${registry_port:8761}/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 10

management:
  security:
    enabled: false
