

camel:
  springboot: 
    main-run-controller: true
  zipkin:
    excludePatterns: "metrics*"
    collector:
      http:
        service:
          host: "{{traceervice_host:zipkinservice}}"
          port: "{{traceervice_port:9411}}"      
#spring:       
#  zipkin: 
#    span: http
#    baseUrl: http://{{traceervice_host:zipkinservice}}:9411/api/v2/spans     
