

camel:
  springboot: 
    main-run-controller: true
  zipkin:
    excludePatterns: "metrics*"
#spring:       
#  zipkin: 
#    span: http
#    baseUrl: http://{{traceervice_host:zipkinservice}}:9411/api/v2/spans     
