jmsexample:
  routes:
    consuming:
    - id: consuming
      entry: jms:queue:customerOne.news.customerTwo
    producing:
    - id: produce
      cron: 0/10+*+*+*+*+?
      exit: jms:queue:customerTwo.news.customerOne
      additionalHeaders:
        foo: faa


camel:
  zipkin:
    server-service-mappings:
      "*" : customer-two
    client-service-mappings:
      "*" : customer-one